name: Andrey Egorov
description: QA Expert

avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
theme: jekyll-theme-minimal

footer-links:
  email: a-n-egorov@yandex.ru
  github: anegorov
  linkedin:
  youtube: # channel/<your_long_string> or user/<user-name>
